# Generated by Django 3.2.6 on 2021-08-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='mysite.section'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subjects',
            field=models.ManyToManyField(blank=True, limit_choices_to=5, null=True, related_name='blogs', to='mysite.Subject'),
        ),
    ]
